### ISSUE TITLE
Remove duplicate bounds checking logic 

### ISSUE THREAD

**Issue by aar10n** [cohere-ai/cohere-go#3]
Since the endpoint options are numeric values instead of pointers, they default to 0 when initializing the struct and an explicit value is not specified. This means that all parameters are included in each request instead of omitting empty ones, and it forces us to ensure that those default values will not produce a 400 response. In the future, we might want to transition to using pointers for our options structs so that `omitempty` can leave out fields which are not specified allowing us to remove the duplicate bounds checking logic.

**Comment by billytrend-cohere** [comment]
Hey thanks for the issue. We now auto-generate the SDKs so the codebase is different and this issue no longer applies.
