### ISSUE TITLE
How to get usage stats from v2.NonStreamedChatResponse

### ISSUE THREAD

**Issue by ahmed-adly-khalil** [cohere-ai/cohere-go#77]
i'm looking at v2.NonStreamedChatResponse and can't find the usage stats (input_tokens\, output_tokens) exposed unless i do `resp.String()`  and unmarshal the json

like this 

```resp, err := client.Chat(context.Background(), &chatReq)

	if err != nil {
		logger.Error("Error chatting with Cohere", zap.Error(err))
		return "", err
	}

	logger.Debug(" Cohere response", zap.Any("resp", resp.String()))
```

any luck with exposing the stats as a prop on the response?

**Comment by billytrend-cohere** [comment]
Hey, taking a look at this!
