### ISSUE TITLE
Support deserialising `BadRequestError` from `Rerank`

### ISSUE THREAD

**Issue by reecerussell** [cohere-ai/cohere-go#79]
Hey Cohere team, I ran into an issue with the SDK when using the Rerank function. I'd like to be able to handle cases where the client returns a Bad Request, however, the SDK only supports returning `core.ApiError` and `cohere.TooManyRequestsError`. I believe this is due to the API documentation only describing responses for 200 and 429 statuses - I was unable to find this documentation online to raise a change to.

It would be great if the Cohere client supports deserialising error responses to all available error types, as it would make handling edge cases a lot nicer, and saves having to dig into the client source code to figure out what is going on.

Many thanks!

**Comment by billytrend-cohere** [comment]
Hey @reecerussell funny you should ask this, I've been trying to document our errors this week! I just released v2.8.2 which has a bunch more error types. Let me know if that works better for you and if you have any other feedback for us. Thanks for reporting this!

**Comment by reecerussell** [comment]
Legend, thanks @billytrend-cohere 🙌🏻
