### ISSUE TITLE
input_type is not an available param for the typed client

### ISSUE THREAD

**Issue by khalid4294** [cohere-ai/cohere-go#88]
Hey! 

I'm trying to embed a text using the typed client and I'm getting this error:
`invalid request: valid input_type must be provided with the provided model (400)`

```
resp, err := Cohere.Embed(
	cohere.EmbedOptions{
		Model: "embed-multilingual-light-v3.0",
		Texts: []string{text},
	},
)
```
there's no parameter for "input_type". Here's the struct from the embed.go:

```
type EmbedOptions struct {
	// An optional string representing the model you'd like to use.
	Model string `json:"model,omitempty"`
	// An array of strings for the model to embed.
	Texts    []string `json:"texts"`
	Truncate string   `json:"truncate"`
}
```

**Comment by billytrend-cohere** [comment]
Hey @khalid4294 which version of the go sdk are you using? InputType should be available. Please see [this example](https://github.com/cohere-ai/cohere-go/blob/abe8044073ed498ffbb206a602d03c2414b64512/tests/sdk_test.go#L197-L203).

**Comment by khalid4294** [comment]
oh, my bad, I didn't see v2. 
this is solved, Thanks!
